name: Build extension

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Test Packaging
        uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@master
        with:
          args: "package"
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2.0.0
      - name: Append date and time to the body
        id: date
        run: NOW=$(date +"%d-%b-%Y %H:%M")"\n\n" >> $GITHUB_ENV
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.PACKAGE_VERSION }}
          artifacts: "*.vsix"
          body: ${{ env.NOW }}${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: true
          replacesArtifacts: true
